config_version = 2

[backdrop]
blur_intensity = 0.39999999105930328

[brightness]
enable_ddcutil = true

    [brightness.monitor.DP-1]
    backend = "ddcutil"

[bar.main]
auto_hide = false
background_opacity = 0.97999997809529305
border = "on_primary"
capsule_group = []
capsule_thickness = 0.64999998919665813
end = [ "tray", "power_profile", "output_volume", "wallpaper", "notifications" ]
font_weight = 700
margin_edge = 0
margin_ends = 0
padding = 14
position = "top"
radius = 0
radius_bottom_right = 10
reserve_space = true
shadow = false
start = [ "workspaces" ]
thickness = 23
widget_spacing = 9

[dock]
active_monitor_only = true
auto_hide = true
icon_size = 26
magnification = false

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "clipboard"

[[control_center.shortcuts]]
type = "session"

[[control_center.shortcuts]]
type = "keyboard_layout"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = false

    [desktop_widgets.widget]

[idle]
pre_action_fade_seconds = 0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-2", "lockscreen-login-box@DP-1", "lockscreen-login-box@winit" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 957.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 961.0
    output = "DP-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 70.0
    box_width = 400.0
    cx = 640.0
    cy = 677.0
    output = "winit"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        show_login_button = true

[shell]
corner_radius_scale = 0.90000001341104507
font_family = "Noto Sans"
screen_time_enabled = true
settings_show_advanced = true

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    open_near_click_launcher = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    session_placement = "floating"
    session_position = "center"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    enabled = false
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "5"
    variant = "destructive"

    [[shell.session.actions]]
    action = "command"
    command = "notify-send 'Noctalia' 'Custom session entry'"
    enabled = false
    variant = "default"

[theme]
builtin = "Kanagawa"
community_palette = "Mine"
source = "wallpaper"
wallpaper_scheme = "m3-monochrome"

[wallpaper]
directory = "/storage/Media"
enabled = true

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/storage/Media/wallpaperflare.com_wallpaper.jpg"

    [wallpaper.last]
    path = "/storage/Media/wallpaperflare.com_wallpaper.jpg"

    [wallpaper.monitors.DP-1]
    path = "/storage/Media/road_asphalt_rain_141217_2560x1080.jpg"

    [wallpaper.monitors.DP-2]
    path = "/storage/Media/wallpaperflare.com_wallpaper.jpg"

    [wallpaper.monitors.winit]
    path = "/storage/Media/wallhaven-yqekql.jpg"

[widget.audio_visualizer]
anchor = true
bands = 128
capsule_radius = 8
color_1 = "on_surface"
color_2 = "on_surface"
mirrored = false
scale = 1.3500000000000001
width = 200.0

[widget.brightness]
scale = 0.80000000000000004
show_label = false

    [widget.brightness.actions]
    scroll_down = "brightness-down 11%"
    scroll_up = "brightness-up 11%"

[widget.clock]
capsule = false
capsule_border = "outline"
capsule_fill = "outline"
capsule_foreground = "outline"
capsule_padding = 4.0
capsule_radius = 19
color = "on_surface"
font_family = "JetBrains Mono Light"
format = "{:%H:%M %a, %d %b}"
scale = 1.0

[widget.control-center]
glyph = "brand-walmart"
scale = 0.90000000000000002

[widget.cpu]
show_value = false
stat = "ram_used"

[widget.input_volume]
show_label = false

[widget.media]
art_size = 18.0
hide_artist = true
interactive = false
max_length = 260
min_length = 155
title_scroll = "none"

[widget.network]
color = "primary"
font_weight = 400
scale = 0.90000000000000013
show_label = false

[widget.notifications]
scale = 0.90000000000000013

[widget.output_volume]
capsule = false
capsule_border = "outline"
capsule_fill = "outline"
capsule_foreground = "outline"
font_weight = 400
scale = 0.90000000000000013
show_label = false

    [widget.output_volume.actions]
    scroll_down = "volume-down 4%"
    scroll_up = "volume-up 4%"

[widget.power_profile]
scale = 0.90000000000000013

[widget.session]
color = "on_surface_variant"
scale = 0.90000000000000002

[widget.spacer_2]
length = 50
type = "spacer"

[widget.spacer_3]
length = 5
type = "spacer"

[widget.spacer_4]
length = 10
type = "spacer"

[widget.tray]
drawer = true
drawer_item_size = 20.0
match_adjacent_spacing = true

[widget.wallpaper]
scale = 0.90000000000000013

[widget.weather]
max_length = 157
scale = 0.90000000000000002
show_condition = false

[widget.workspaces]
active_pill_size = 1.6000000000000001
capsule_fill = "outline"
capsule_opacity = 0.59999999999999998
capsule_padding = 14.0
capsule_radius = 3
label_source = "id"
show_labels = true
empty_color = "shadow"
focused_color = "primary"
font_family = "JetBrains Mono ExtraBold"
occupied_color = "shadow"
scale = 1.0
